### ISSUE TITLE
Storybook examples are not authenticated after env file updates

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#235]
After updating our storybook examples to use env variables, the examples no longer load: https://storybook.justifi.ai/?path=/story/pre-release-components-paymentslist--basic

**Comment by colganmeanor** [comment]
@jakemer - I had to think about this because I was a little confused - but I realize why this is broken. 

When we merged [PR#221 - Env files](https://github.com/justifi-tech/web-component-library/pull/221)  we merged that branch into `release.10.4.23` and NOT into `main`

So, on `main` we are simply seeing that the token is expired. Since the release branch isn't ready quite yet, I am going to hotfix this by simply adjusting the value on the config file that is currently being used to supply this value.
