### ISSUE TITLE
please add variable for input fields sperately so that we can add style (width) seperately

### ISSUE THREAD

**Issue by qayyumgb** [justifi-tech/web-component-library#251]
I need to make the payement form same like wepay

**Comment by jakemer** [comment]
Hello @qayyumgb -
The goal with our web components is to make it very quick and easy for our customers to integrate and accomplish common use cases. When using the `PaymentForm` our customers don't need to worry about validing payment method info, tokenizing it into a payment method, and it also can keep your application out of PCI scope. It provides huge time savings.

The trade-off, however, is that it is not fully customizable. If you need a payment form with a custom layout, you may consider pairing your own custom front-end to our APIs instead of using the component.
