### ISSUE TITLE
Checkout component: label color variable not working

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#566]
**Describe the bug**
In the checkout component the color set by the `jfi-form-label-color` variable is not applied to the card form and bank account form.
component version: 4.15.0

**Expected behavior**
The color set in the variable is applied to all form labels.

**Screenshots**
![image001](https://github.com/justifi-tech/web-component-library/assets/15485124/28b775b2-3973-4c52-8805-46ea121b7667)

**Comment by colganmeanor** [comment]
Hey @Claudia108 - 

I was looking into this earlier today and I was unable to reproduce this behavior. 

We tested with a sample app today and were successfully able to apply the styles to the labels on the Card and Bank form using the `--jfi-form-label-color` css variable. 

I'd just want to make sure that the customer who reported the issue is applying the styles correctly. As a reminder:

In their CSS / SCSS file, they must wrap their styles for the web components in a block that targets root: 

Example:
```
:root {
  --jfi-form-label-color: rgb(138, 42, 35);
}
```

And importantly: the stylesheet must be present before the component loads. Based on what you reported here, I'm wondering if this could be a case where the styles are loading after the component loads, which may not be passed correctly to the iframe'd payments-js code here. 🤔
